### ISSUE TITLE
Remove Create/Delete Configuration procedures if they are not needed

### ISSUE THREAD

**Issue by urvashisingh** [electric-cloud/EC-Puppet#13]
Looking at the commit logs, these procedures were added with the assumption that "that we will need these two fields for the Puppet Master configuration in ElectricFlow. Puppet Master URL
and Auto join {true/false}"

But I don't see the configurations being used in any of the newly added procedures. Can we remove the Create/Delete Configuration procedures if they are not needed? If this is done, the corresponding release note in the help file should also be removed.

**Comment by aavinashjha** [comment]
Configurations can be set( which overwrites puppet.conf file).
This link shows that it was first presented in Puppet Enterprise( Not present in opensource puppet ).
https://docs.puppetlabs.com/pe/3.2/config_set.html
There are many configurations as you find in this link:
https://docs.puppetlabs.com/puppet/latest/reference/configuration.html
Right now we are not using them, but it will be beneficial if we shift to other versions of puppet which support setting configurations in future.

**Comment by urvashisingh** [comment]
You bring up an interesting point. When do users typically pick Puppet Enterprise over opensource puppet? Would the plugin work with Puppet Enterprise out-of-the-box or would we need to make changes.
Going back to Configurations, are you planning to refactor the existing procedures and use the configuration procedures? If not, lets remove them. They will raise unnecessary questions from users on the purpose of these procedures if they are not being used.

**Comment by aavinashjha** [comment]
We found out that we were running an older version of puppet(3.4.3) which did not supported setting configurations. The later versions(>=3.5) (of opensource puppet) supports setting configurations as could be seen in the links below.
https://docs.puppetlabs.com/puppet/3.5/reference/config_set.html#
https://docs.puppetlabs.com/pe/3.2/config_set.html#

Puppet enterprise comprises of all the features of open source Puppet plus some other enterprise enhancements. Our plugin will work perfectly for both Puppet Enterprise and Opensource.

As per the configuration procedures are concerned, we are required to add one configuration Procedure(That at backend will run command like puppet config set server <SERVER_NAME>) and the existing configuration procedures(CreateConfiguration and DeleteConfiguration) could be removed. 

This procedure will comprise of setting following important configurations:
http://docs.puppetlabs.com/puppet/3.5/reference/config_important_settings.html

**Comment by urvashisingh** [comment]
Closing the issue. Create/Delete Configuration procedures have been removed.
