### ISSUE TITLE
Clean up the labels for the procedures

### ISSUE THREAD

**Issue by urvashisingh** [electric-cloud/EC-Puppet#15]
Let us use user-friendly labels for the procedure parameters. Some of the changes I would recommend are:
for RunAgent procedure:
  CertName - Certificate Name for the client
   WaitForCert - Wait for the client certificate to be signed
   Detailed-Exitcodes - I am not sure what to call this one yet
   Additional-Options - Additional Options

Please review other procedures and clean up the labels. General rules to follow while creating labels:
1. Readability - spaces between words, self explanatory
2. Use Puppet terminology where possible
3. No typos, upper case nouns

**Comment by chanijindal1** [comment]
Corrected the labels .
