### ISSUE TITLE
Remove irrelevant check-box fields in RunAgent procedure

### ISSUE THREAD

**Issue by urvashisingh** [electric-cloud/EC-Puppet#16]
Remove some of these check-box fields in the RunAgent procedure. Ask only for relevant input for applying client configuration to the agent. 
  o Daemonize and No-Daemonize: Keep one of these. Default the field value to whatever is reasonable or default for Puppet 
  o Enable and Disable: Same as above 
  o Help, Verbose - Remove both of these. Users can use 'Additional Options' field to pass these flags if needed. 
  o Debug - Keep only if this is being used to control the debug logs in the procedure script.

**Comment by chanijindal1** [comment]
Removed daemonize checkbox for RunAgent procedure and help option for all.
Did not remove the debug option as it comes in handy for debugging after procedure runs.
Did not remove Enable,Disable as the options are not run specific . Result persists between the runs .
For example user may want to enable working on local system , after disabling the same or vise versa.
