### ISSUE TITLE
Support for working with environments and node groups

### ISSUE THREAD

**Issue by urvashisingh** [electric-cloud/EC-Puppet#18]
I am trying to understand how the EC-Puppet procedures, in particular RunAgent can be used to setup a node for a particular envt say "apache web servers for staging" or "mysql for production". It not clear to me how the procedures can be used to achieve this. 
I found this document on puppetlabs https://docs.puppetlabs.com/pe/latest/console_classes_groups_environment_override.html which describes the workflow that can be used. How can we achieve this (or if there is another approach that puppet follows) with the plugin?

**Comment by aavinashjha** [comment]
Please refer this configuration issue comment :
https://github.com/electric-cloud/EC-Puppet/issues/13

Environments are also handled by editing puppet.conf file. 
http://www.allgoodbits.org/articles/view/38
But changing configurations with command line using puppet is not supported in opensource puppet. Right now that could be done manually as we don't have config set present or we could write code to change configurations in the puppet.conf file, but that will be without using puppet provided way to change configurations.
As could be seen no action called set.
USAGE: puppet config <action> 

Interact with Puppet's configuration options.

OPTIONS:
  --render-as FORMAT             - The rendering format to use.
  --verbose                      - Whether to log verbosely.
  --debug                        - Whether to log debug information.

ACTIONS:
  print    Examine Puppet's current configuration settings.

See 'puppet man config' or 'man puppet-config' for full help.

**Comment by urvashisingh** [comment]
I didn't get this. Are you saying that "puppet config" is the way to change the node's environment and that is it not supported with open source puppet? In that case, can we update the puppet.conf to assign an envt to the puppet node?

**Comment by aavinashjha** [comment]
Yes, you are right. We can specify a node's environment by setting its puppet configuration as shown in the link below.
https://docs.puppetlabs.com/puppet/3.5/reference/configuration.html#environment
As newer versions of puppet allow us to set configurations, we are good to specify environments for node by using our new ConfigurationSet Procedure, which we we will be adding.
https://github.com/electric-cloud/EC-Puppet/issues/13

**Comment by aavinashjha** [comment]
Added UpdateAgentConfiguration Procedure to address this.
